FROM golang:1.25.4

WORKDIR /app

COPY worker/go.mod worker/go.sum ./worker/

# Copy any shared code
COPY shared ./shared

WORKDIR /app/worker

# Download dependencies
RUN go mod download

COPY worker/ .

# Copy wordmap asset
COPY shared/assets/4-WordMap.json /app/assets/4-WordMap.json

# Build the server
RUN go build -o /worker

EXPOSE 8080

# Run the executable
CMD ["/worker"]