FROM golang:1.25.4

WORKDIR /app

COPY game-service/go.mod game-service/go.sum ./game-service/

# Copy shared modules
COPY shared/ ./shared/

WORKDIR /app/game-service

# Download dependencies
RUN go mod download

COPY game-service/ .

# Copy wordmap asset
COPY shared/assets/4-WordMap.json /app/assets/4-WordMap.json

# Build the server
RUN go build -o /game-service

EXPOSE 8080

# Run the executable
CMD ["/game-service"]