FROM golang:1.25.4

WORKDIR /app

COPY parrot/go.mod parrot/go.sum ./parrot/

WORKDIR /app/parrot

# Download dependencies
RUN go mod download

COPY parrot/ .

# Build the server
RUN go build -o /parrot

EXPOSE 8080

# Run the executable
CMD ["/parrot"]